server:
  port: 8080

#logging:
#  level:
#    root: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
#    enabled: false
#  api-docs:
#    enabled: false
#    path: /api-docs
#    url: /v3/api-docs
#    config-url: /mySpringdocConfig



