spring:
  datasource:
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruoyi-vue-pro
    username: root
    password: root
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

