server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-client2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/config-server
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
management:
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

caffeine:
  configs:
    - cacheName: short-term-cache
      initialCapacity: ${initial-capacity:100}
      maximumSize: 500
      expireAfterWriteMins: 90
    - cacheName: long-term-cache
      initialCapacity: 5
      maximumSize: 50
      expireAfterWriteMins: 300


layering:
  - cacheName: short-term-cache
    caffeine:
      initialCapacity: 50
      maximumSize: 500
      expireAfterWriteMins: 90
    redis:
      preloadTime: 50
      expirationTime: 30
      forceRefresh: false
      usePrefix: true
      enablePrimaryCache: true