server:
  port: 48080
#  servlet:
#    context-path: /admin-api

logging:
  level:
    root: info
    org:
      redisson:
        command:
          RedisExecutor: info
      hibernate:
        stat: DEBUG
spring:
  profiles:
    active: redis,shardingsphere,jpa
  application:
    name: spring-creed-server
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ruoyi-vue-pro
    username: root
    password: root

  main:
    allow-circular-references: true
#    lazy-initialization: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        generate_statistics: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  thymeleaf:
    enabled: true
    cache: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    cache-duration: 1s

  servlet:
    multipart:
#      location: ${ms.app.home.dir}/tmp
      max-file-size: 10MB
      file-size-threshold: 10MB
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true
#    enabled: false
#  api-docs:
#    enabled: false
#    path: /api-docs
#    url: /v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"


#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: okta-client-id
#            client-secret: okta-client-secret
#            authorization-grant-type: client_credentials
#            scope: read, write
#        provider:
#          okta:
#            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token


creed:
  security:
    permitAllUrls:
      - /admin-ui/** # /resources/admin-ui 目录下的静态资源
#      - /admin-api/**
    mock-enable: true


leaf:
  name: com.ethan.leaf.test
  console:
    enable: true
  segment:
    enable: true
  snowflake:
    worker-id:
      default: 1
    enable: true