
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        generate_statistics: true #统计数据
logging:
  level:
    org.hibernate.orm: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG