# 配置真实数据源
spring:
  shardingsphere:
    datasource:
      names:
        - master
        - slaver1
        - slaver2
      # 配置第 1 个数据源
      master:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
        username: root
        password:
      # 配置第 2 个数据源
      slaver1:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
        username: root
        password:
      # 配置第 3 个数据源
      slaver2:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
        username: root
        password:
    props:
      sql:
        show: true # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
      sql-show: true
    rules:
      readwrite-splitting:
        data-sources:
          master:
            write-data-source-name: master
            read-data-source-names:
              - slaver1
              - slaver2
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
            props:
              transaction-read-query-strategy: FIXED_PRIMARY



# 负载均衡算法配置
#  spring.shardingsphere.rules.readwrite-splitting.load-balancers.<load-balance-algorithm-name>.type= # 负载均衡算法类型
#  spring.shardingsphere.rules.readwrite-splitting.load-balancers.<load-balance-algorithm-name>.props.xxx= # 负载均衡算法属性配置