# curl 'http://localhost:48080/admin-api/system/notice/page?pageNo=1&pageSize=10&title='
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/notice/page?pageNo=1&pageSize=10&title=
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###
#{"code":0,"data":{"list":[{"title":"维护通知：2018-07-01 若依系统凌晨维护","type":2,"content":"<p><img src=\"http://test.yudao.iocoder.cn/b7cb3cf49b4b3258bf7309a09dd2f4e5.jpg\">维护内容</p>","status":1,"id":2,"createTime":1609837428000},{"title":"芋道的公众","type":1,"content":"<p>新版本内容133</p>","status":0,"id":1,"createTime":1609837428000}],"total":2},"msg":""}


# curl 'http://localhost:48080/admin-api/system/notice/get?id=2'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/notice/get?id=2
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###
#{"code":0,"data":{"title":"维护通知：2018-07-01 若依系统凌晨维护","type":2,"content":"<p><img src=\"http://test.yudao.iocoder.cn/b7cb3cf49b4b3258bf7309a09dd2f4e5.jpg\">维护内容</p>","status":1,"id":2,"createTime":1609837428000},"msg":""}


# curl 'http://localhost:48080/admin-api/system/notice/update'
#  -X 'PUT'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --data-raw '{"title":"维护通知：2018-07-01 若依系统凌晨维护","type":2,"content":"<p><img src=\"http://test.yudao.iocoder.cn/b7cb3cf49b4b3258bf7309a09dd2f4e5.jpg\">维护内容</p>","status":0,"id":2,"createTime":1609837428000}'
#  --compressed
PUT http://localhost:48080/admin-api/system/notice/update
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer e5e8c44f7c8d4dc3bab84a33221fdb0a
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1
Content-Type: application/json

{
  "title": "维护通知：2018-07-01 若依系统凌晨维护",
  "type": 2,
  "content": "<p><img src=\"http://test.yudao.iocoder.cn/b7cb3cf49b4b3258bf7309a09dd2f4e5.jpg\">维护内容</p>",
  "status":0,
  "id":2,
  "createTime":1609837428000}

###
#{"code":0,"data":true,"msg":""}
