server:
  port: 8040

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop100:3306/creed_mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    open: false
    database: 0     # Redis 数据库号，默认为 0
    host: hadoop100
    port: 6379
    timeout: 5000s  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0  #连接池中的最小空闲连接
      shutdown-timeout: 100 # 关闭超时时间
  cloud:
    nacos:
      discovery:
        server-addr: hadoop100:8848

mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #逻辑已删除值(默认1), 配合@TableLogic
      logic-not-delete-value: 0 #逻辑未删除值(默认0)

logging:
  level:
    com:
    ethan:
      creedmall:
        product: debug