#
#
#caffeine:
#  configs:
#    - cacheName: permission-cache
#      initialCapacity: 50
#      maximumSize: 500
#      expireTime: 599
#      timeUnit: seconds
#      expireMode: EXPIRE_AFTER_WRITE
#      weakKeys: false