spring:
  gradation:
    cache_user:
      depict: "用户缓存"
      useFirstCache: true
      allowNullValue: false
      caffeineCache:
        initialCapacity: 20
        maximumSize: 500
        expireTime: 599
        timeUnit: seconds
        expireMode: EXPIRE_AFTER_ACCESS
        stats: false
        weakValues: true
        weakKeys: false
      redisCache:
        expiration: 1199
        preloadTime: 24
        timeUnit: MINUTES
        forceRefresh: false
        usePrefix: true
        magnification: 1
        stats: false
    cache_blog:
      depict: "博客缓存"
      allow-null-value: true
      use-first-cache: false
      caffeineCache:
        initial-capacity: 11
        expire-time: 11
        maximum-size: 100
        time-unit: seconds
        expire-mode: expire_after_write
        stats: false
      redisCache:
        expiration: 11
        preload-time: 22
        time-unit: seconds
