spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mariadb://localhost:3306/jpa_lock
    username: root
    password:
    hikari:
      connection-timeout: 300000
      maximum-pool-size: 50
  #    driver-class-name: org.h2.Driver
##    schema: classpath:db/schema-h2.sql
##    data: classpath:db/data-h2.sql
#    url: jdbc:h2:~/test
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
logging:
  file:
    name: /logs/creed/spring-creed-jpa.log
