server:
  ssl:
    client-auth: need
    enabled: true
#    key-store: classpath:ssl/verify/creed-mall-server.jks
#    key-store-password: changeit
#    trust-store: classpath:ssl/verify/creed-mall-server-truststore.jks
#    trust-store-password: changeit
    key-store: classpath:ssl/creed-mall-server.jks
    key-store-password: changeit
    trust-store: classpath:ssl/creed-mall-server-truststore.jks
    trust-store-password: changeit
    enabled-protocols: TLSv1.2,TLSv1.3
    protocol: TLS

