###

# curl --location --request POST 'localhost:8088/v2/person/student'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "username":"xiaoming",
#    "gender":"male",
#    "age":18
#}'
POST localhost:8088/v2/person/student
Content-Type: application/json

{
  "username": "xiaoming",
  "gender": "male",
  "age": 18
}

###

POST localhost:8088/price/info
Content-Type: application/json

{
  "userInfo": {
    "name": "xiaomi",
    "locked": false,
    "active": true
  },
  "coupon": {
    "userName": "xiaomi",
    "discount": "2.00"
  },
  "activityInfo": {
    "productName": "mobile",
    "discountPercentage": "10"
  },
  "productInfo": {
    "productName": "mobile",
    "brand": "xiaomi",
    "description": "this is a mobile phone",
    "stock": 2,
    "price": "1000.00"
  }
}

