server:
  port: 88

management:
  endpoints:
    web:
      exposure:
        include: gateway
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true

spring:
  cloud:
    nacos:
      discovery:
        server-addr: hadoop100:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://creedmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug