spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/auth
    password:
    username: root

  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#  jpa:
#    hibernate:
#      ddl-auto: update
server:
  port: 8080

logging:
  level:
    #    root: debug
    root: trace
    org.apache.tomcat: info


