
server:
  tomcat:
    threads:
      max: 10
      max-queue-capacity: 5
    accesslog:
      enabled: true
#    basedir: ./workspace/sourcecode/ethan-space/spring-creed

logging:
  file:
    name: ./logs/${logging.instance:${spring.application.name:}}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
spring:
  application:
    name: local-cache


