
server:
  tomcat:
    threads:
      max: 10
      max-queue-capacity: 5
    accesslog:
      enabled: true
      directory: ../logs
      class-name: org.apache.catalina.valves.AccessLogValve
      buffered: false
      suffix: .log
      rotate: true
      max-days: 15
      encoding: UTF-8
      file-date-format: -yyyy-MM-dd
      request-attributes-enabled: true
#      pattern: "%{yyyy-MM-dd HH:mm:ss.SSS}t %h %r %s %b [%{ms}T ms] [%{x-b3-traceid}i,%{x-b3-spanid}i]"
      pattern: "%{yyyy-MM-dd HH:mm:ss.SSS}t %h %r %s %b [%F ms] [%{x-b3-traceid}i,%{x-b3-spanid}i]"

logging:
  file:
    name: ./logs/${logging.instance:${spring.application.name:}}.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
spring:
  application:
    name: local-cache


