# curl 'http://localhost:48080/admin-api/system/sensitive-word/page?pageNo=1&pageSize=10'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/sensitive-word/page?pageNo=1&pageSize=10
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###

#{"code":0,"data":{"list":[{"name":"白痴","tags":["测试"],"status":0,"description":null,"id":5,"createTime":1672484905000},{"name":"XXX","tags":["短信"],"status":0,"description":null,"id":4,"createTime":1649424469000},{"name":"土豆","tags":["蔬菜","短信"],"status":0,"description":"好呀","id":3,"createTime":1649423232000}],"total":3},"msg":""}

# curl 'http://localhost:48080/admin-api/system/sensitive-word/get-tags'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/sensitive-word/get-tags
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###
#{"code":0,"data":["蔬菜","测试","短信"],"msg":""}


# curl 'http://localhost:48080/admin-api/system/sensitive-word/validate-text?text=%E4%BD%A0%E6%98%AF%E4%B8%8D%E6%98%AF%E7%99%BD%E7%97%B4&tags=%E6%B5%8B%E8%AF%95'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/sensitive-word/validate-text?
    text=你是不是白痴&tags=测试
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###
#{"code":0,"data":["白痴"],"msg":""}


# curl 'http://localhost:48080/admin-api/system/sensitive-word/get?id=4'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --compressed
GET http://localhost:48080/admin-api/system/sensitive-word/get?id=4
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1

###
#{"code":0,"data":{"name":"XXX","tags":["短信"],"status":0,"description":null,"id":4,"createTime":1649424469000},"msg":""}

# curl 'http://localhost:48080/admin-api/system/sensitive-word/update'
#  -X 'PUT'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost:4200'
#  -H 'Referer: http://localhost:4200/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82'
#  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Windows"'
#  -H 'tenant-id: 1'
#  --data-raw '{"name":"XXX","tags":["短信"],"status":0,"description":"remark","id":4,"createTime":1649424469000}'
#  --compressed
PUT http://localhost:48080/admin-api/system/sensitive-word/update
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer 33436a81f7b24e36a582c3a7f2c86fd2
Connection: keep-alive
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Microsoft Edge";v="114"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
tenant-id: 1
Content-Type: application/json

{
  "name": "XXX",
  "tags": [
    "短信"
  ],
  "status": 0,
  "description": "remark",
  "id": 4,
  "createTime": 1649424469000
}

###
{"code":0,"data":true,"msg":""}



