

spring:
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 10

#management:
#  endpoints:
#    web:
#      exposure:
logging:
  level:
#    root: debug
    root: trace
    org.apache.tomcat: info
#management:
#  server:
#    port: 8088
#        include: *