spring:
  shardingsphere:
    datasource:
      names: ds-orders, ds-users # 所有数据源的名字
      ds-orders:
        data: classpath:db/data-h2.sql
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:~/ds-orders
        username: sa
        password:
      ds-users:
        data: classpath:db/data-h2.sql
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:~/ds-users
        username: sa
        password:
    # 分片规则
    sharding:
      tables:
        # orders 表配置
        orders:
          actualDataNodes: ds-orders.orders # 映射到 ds-orders 数据源的 orders 表
        # users 表配置
        users:
          actualDataNodes: ds-users.users # 映射到 ds-users 数据源的 users 表
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    data: classpath:db/data-h2.sql

#  datasource:
#    driver-class-name: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
##    data: classpath:db/data-h2.sql
#    url: jdbc:h2:~/test
#    username: sa
#    password:
