spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    data: classpath:db/data-h2.sql
    url: jdbc:h2:~/test
    username: sa
    password: