spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    data: classpath:db/data-h2.sql
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#  redis:
#    database: 0     # Redis 数据库号，默认为 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000s  # 连接超时时长（毫秒）
#    lettuce:
#      pool:
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8  #连接池中的最大空闲连接
#        max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
#        min-idle: 0  #连接池中的最小空闲连接
#      shutdown-timeout: 100 # 关闭超时时间

multi:
  redis:
    redisSession:
      database: 10     # Redis 数据库号，默认为 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000s  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 2 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 2  #连接池中的最大空闲连接
          max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
          min-idle: 0  #连接池中的最小空闲连接
        shutdown-timeout: 100 # 关闭超时时间
    redisOAuth:
      database: 1     # Redis 数据库号，默认为 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000s  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 2 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 2  #连接池中的最大空闲连接
          max-wait: -1s #连接池最大阻塞等待时间（使用负值表示没有限制)
          min-idle: 0  #连接池中的最小空闲连接
        shutdown-timeout: 100 # 关闭超时时间

logging:
  config: classpath:logback-spring.xml
  dir: ${user.dir}
  level:
    root: debug