spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ruoyi-vue-pro
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  web:
#    resources:
#      static-locations: classpath:/static/